///<reference types= "Cypress"/>

const { rgb } = require("color-convert")

before(()=>{
   console.log('running my tests')
})

beforeEach(()=>{
  cy.visit('https://tradeoxy.com/')
})

it('Google Search',()=>{
  cy.viewport(1280,720)
  cy.get('a > .shrink-0').should('be.visible')
  cy.get('[data-title="Youtube Video"]').should('exist')
  cy.get('.opacity-100').should('exist').click()
  cy.get('#dialog-close').click()
  cy.get('a[href="/pricing/"]').should('exist')
  //cy.get('a[href="/pricing/"]').click({force:true})
  //cy.go('back')
  cy.get('a[href="/signin/"]').click()
  cy.get(':nth-child(4) > .text-white').click()
  cy.get('[name="email"]').type("abc@xyz.com")
  cy.get('[name="password"]').type("abc12345")
  cy.get('[class="opacity-100"]').click()
  cy.get('a[href="/forgot/"]').click()
  cy.get('[name="email"]').type("abc@xyz.com")
  cy.get('.opacity-100').click()
  cy.get('a > .flex > .text-center').click()
  cy.get('a[href="/signup/"]').click()
  cy.wait(6000)
  cy.get('.flex-col > :nth-child(4)').click()
  cy.wait(6000)
  cy.get('[name="name"]').type("John Doe")
  cy.get('[name="email"]').type("rose1234@gmail.com")
  cy.get('[name="password"]').type("Rose1234")
  cy.get('[name="confirmPassword"]').type("Rose1234")
  cy.get('.opacity-100').click()
  cy.get('a[href="/signin/"]').click()
  cy.get(':nth-child(4) > .text-white').click()
  cy.get('[name="email"]').type("rose1234@gmail.com")
  cy.get('[name="password"]').type("Rose1234")
  cy.get('[class="opacity-100"]').click()
  cy.wait(5000)
  cy.get('.px-10 > .text-center').click({force:true})
  cy.wait(5000)
  cy.get('.opacity-100').click()
  cy.get('.gap-7 > :nth-child(1) > .grow').contains('Scanners').trigger('mouseover')
  cy.wait(5000)
  cy.get('a[href="/?scanner=crypto/"]').should('be.visible').click({force:true}) 
  cy.get('.gap-7 > :nth-child(1) > .grow').contains('Scanners').trigger('mouseover')
  cy.get('a[href="/?scanner=stock/"]').should('exist').click({force:true})
  cy.get('.gap-7 > :nth-child(1) > .grow').contains('Scanners').trigger('mouseover')
  cy.get('a[href="/?scanner=forex/"]').should('exist').click({force:true})
  
})